version: '3.8'
services:
  app:
    container_name: tasktracker-postgresql
    image: tasktracker-postgresql
    build: ./
    ports:
      - '49160:3000'
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskTracker
