version: '3'
services:
  web:
    container_name: tasktracker-postgresql
    image: tasktracker-postgresql
    build: .
    ports:
      - '3000:3000'
    links: 
      - dbpostgresql
  dbpostgresql:
    image: postgres:12.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1'
      POSTGRES_DB: 'taskTracker'
